a = int(input("Enter a number :"))
b = int(input("Enter the second Number :"))

print("Addition :",a+b)
print("subtraction :",a-b)
print("Multiplication :",a*b)
print("Divison :",a/b)
print("Modulus :",a%b)
print("Floor Divison :",a//b)
print("power :",a**b)